# Generated by Django 2.2.6 on 2019-10-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('fase', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenha', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=8)),
                ('permiso', models.CharField(max_length=15)),
                ('rol', models.CharField(max_length=15)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionItem.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linea_base', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('enunciado', models.CharField(max_length=400)),
                ('tarea', models.CharField(max_length=50)),
                ('duenho_voluntario', models.CharField(max_length=60)),
                ('horas_estimadas', models.PositiveSmallIntegerField()),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionItem.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=400)),
                ('prioridad', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('atributo', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('observacion', models.CharField(max_length=400)),
                ('id_linea_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionItem.LineaBase')),
                ('id_usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionItem.Usuario')),
            ],
        ),
    ]
