# Generated by Django 2.2.6 on 2019-10-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0002_auto_20191024_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('A', 'Analisis'), ('D', 'Diseño')], max_length=13),
        ),
    ]
