# Generated by Django 2.2.6 on 2019-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0004_auto_20191028_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inacivo')], max_length=8),
        ),
    ]
