# Generated by Django 2.2.6 on 2019-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0005_auto_20191028_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('L', 'Lider de Proyecto'), ('D', 'Desarrollador')], max_length=15),
        ),
    ]
