# Generated by Django 2.2.6 on 2019-11-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0007_auto_20191108_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionItem.Proyecto'),
        ),
    ]
