# Generated by Django 2.2.6 on 2019-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0011_auto_20191115_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=10),
        ),
    ]
