# Generated by Django 2.2.6 on 2019-11-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0012_auto_20191115_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='none ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula_identidad',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='ninguno', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inacivo')], default='Activo', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionItem.Proyecto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.CharField(default='ninguno', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('L', 'Lider de Proyecto'), ('D', 'Desarrollador')], default='ninguno', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='observacion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='item',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=15),
        ),
    ]
