# Generated by Django 2.2.6 on 2019-12-13 22:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('gestionItem', '0013_auto_20191115_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Rol',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lineabase',
            options={'ordering': ['id'], 'verbose_name_plural': 'Lineas Bases'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('D', 'Desarrollador'), ('P', 'Product Owner'), ('S', 'Scrum Master')], max_length=15),
        ),
    ]
