# Generated by Django 2.2.6 on 2019-12-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0014_auto_20191213_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
