# Generated by Django 2.2.6 on 2019-12-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionItem', '0015_delete_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineabase',
            old_name='duenho_voluntario',
            new_name='responsable',
        ),
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('I', 'Por iniciar'), ('R', 'En revision'), ('F', 'Finalizado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='estado',
            field=models.CharField(choices=[('I', 'Por iniciar'), ('A', 'Activo'), ('C', 'Cerrado')], max_length=15),
        ),
    ]
